# Generated by Django 6.0.3 on 2026-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.UUIDField(unique=True)),
                ('seed', models.IntegerField(default=1337)),
                ('biome', models.CharField(default='TEMPERATE', max_length=30)),
                ('radius', models.FloatField(default=1000.0)),
            ],
        ),
    ]
